apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-microservice-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: auth-microservice
  endpoints:
  - port: http
    interval: 10s
    path: /metrics
